// frontend/digital-twin-panel/src/App.svelte
<script lang="ts">
  import { Route, Router } from "svelte-routing";
  import getRoutes from "./app/config/routes/routes";
  import Page404 from "./lib/infraestructure/presentation/pages/error/Page404.svelte";

  const routes = getRoutes();
</script>

<Router>
  {#each routes as route}
    <Route path={route.path}>
      <svelte:component this={route.layout}>
        <svelte:component this={route.component} />
      </svelte:component>
    </Route>
  {/each}
  <Route component={Page404} />
</Router>

// digital-twin-panel/src/App.tsx
import { BrowserRouter, Route, Routes } from "react-router-dom";
import { getRoutes } from "./app/config/routes/routes";
import { Page404 } from "./infraestructure/delivery/presentation/pages/Page404";

function App() {
  return (
    <BrowserRouter basename="/">
      <Routes>
        {getRoutes(true).map((route, index) => (
          <Route
            key={index}
            path={route.path}
            element={
              <route.layout>
                <route.component />
              </route.layout>
            }
          />
        ))}
        <Route path="*" element={<Page404 />} />
      </Routes>
    </BrowserRouter>
  );
}

export default App;
