// frontend/panel/src/content/applications/Overview/Partnership.tsx
import {
  alpha,
  Box,
  Container,
  Divider,
  Grid,
  styled,
  Typography,
} from "@mui/material";

const Partnership = () => {
  const MuiAvatar = styled(Box)(
    ({ theme }) => `
    width: 175px;
    height: 175px;
    border-radius: ${theme.general.borderRadius};
    background-color: ${alpha(theme.colors.secondary.light, 0.15)};
    flex-shrink: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    margin: 0 auto ${theme.spacing(2)};
    img {
      width: 150px;
      display: block;
    }
    &:hover {
       transition: box-shadow 0.1s ease-in-out !important;
        box-shadow: 0 6px 10px rgba(0,0,0, 0.2);
    }
`
  );

  const logosPath = [
    {
      path: "/static/images/overview/virtalis-logo.png",
      link: "https://www.vitartis.es/",
    },
    {
      path: "/static/images/overview/7edata-logo.png",
      link: "https://www.7edata.com/",
    },
    {
      path: "/static/images/overview/agrointelligent-logo.webp",
      link: "https://www.agrointelligent.com/",
    },
    {
      path: "/static/images/overview/geoslab-logo.png",
      link: "https://www.geoslab.com/",
    },
    {
      path: "/static/images/overview/campg-logo.png",
      link: "https://campag.es/",
    },
    {
      path: "/static/images/overview/pystacil-logo.png",
      link: "https://pistacyl.com/",
    },
    {
      path: "/static/images/overview/cetemet-logo.png",
      link: "https://cetemet.es/",
    },
  ];

  return (
    <Container maxWidth="md" sx={{ textAlign: "center" }}>
      <Container maxWidth="md" sx={{ textAlign: "center", mt: 4 }}>
        <Divider
          variant="middle"
          sx={{ height: 2, m: 10, backgroundColor: "#A1A1A1" }}
        />
        <Typography variant="h1">Socios</Typography>
        <Typography
          component="p"
          variant="subtitle2"
          sx={{ fontSize: 20, mt: 2 }}
        >
          El consorcio que lleva a cabo el proyecto está formado por un total de
          siete entidades: dos clústers, un centro tecnológico, dos pymes y una
          startup de base tecnológica y una empresa agroalimentaria.
        </Typography>
      </Container>
      <Grid
        container
        spacing={1}
        mt={5}
        alignItems="top"
        justifyContent="center"
      >
        {logosPath.map(({ path, link }) => (
          <Grid item md={3} key={path}>
            <a href={link}>
              <MuiAvatar className="reveal-from-bottom-animation">
                <img src={path} width={200} />
              </MuiAvatar>
            </a>
          </Grid>
        ))}
      </Grid>
    </Container>
  );
};

export default Partnership;

// frontend/web-app/src/lib/components/landing-page/partnership.svelte
<script lang="ts">
	export let partners: any[] = [];
	export let phase: string = '';
</script>

<section>
	<div class="container-sm reveal-from-bottom" data-reveal-delay="150" data-reveal-offset="250">
		<div class="features-tiles-inner section-inner has-bottom-divider">
			<div class="container-xs">
				<h2 class="mt-0 mb-16 reveal-from-bottom" data-reveal-delay="100">Socios</h2>
				<p class="m-0">
					El consorcio que lleva a cabo la {phase} del proyecto está formado por las siguientes entidades.
				</p>
			</div>
			<div class="tiles-wrap">
				{#each partners as { path, link }, i}
					<a style="border: none;" href={link} rel="noreferrer" target="_blank">
						<div class="img-wrapper">
							<img
								loading="lazy"
								alt={link}
								style="object-fit: contain;"
								src={`${path}`}
								width={175}
								height={150}
							/>
						</div>
					</a>
				{/each}
			</div>
		</div>
	</div>
</section>

<style lang="scss">
	section {
		display: grid;
		place-items: center;
		text-align: center;
		margin-top: 4rem;

		.features-tiles-inner {
			padding-top: 0;
			display: grid;
			place-items: center;
		}

		.tiles-wrap {
			display: flex;
			flex-wrap: wrap;
			justify-content: center;
			align-items: center;
			column-gap: 2rem;
			row-gap: 1rem;
			margin-top: 3rem;
			margin-bottom: 6rem;

			.img-wrapper {
				background-color: color-bg(body);
				padding: 1rem;
				border-radius: 0.5rem;

				&:hover {
					transition: all 0.2s ease-in-out;
					box-shadow: 0 0 0 0.2rem rgba(0, 0, 0, 0.1), color-bg(shadow-light);
				}
			}
		}
	}

	@include media('<medium') {
		section {
			.tiles-wrap {
				img {
					width: 150px;
					height: 125px;
				}
			}
		}
	}
</style>
