// frontend/digital-twin-panel/src/App.svelte
<script lang="ts">
  import { Route, Router } from "svelte-routing";
  import getRoutes from "./app/config/routes/routes";
  import Page404 from "./lib/infraestructure/presentation/pages/error/Page404.svelte";

  const routes = getRoutes();
</script>

<Router>
  {#each routes as route}
    <Route path={route.path}>
      <svelte:component this={route.layout}>
        <svelte:component this={route.component} />
      </svelte:component>
    </Route>
  {/each}
  <Route component={Page404} />
</Router>

// frontend/digital-twin-panel/src/App.tsx
import { useEffect } from "react";
import { useSelector } from "react-redux";
import { BrowserRouter, Route, Routes } from "react-router-dom";
import {
  doFetchParcels,
  doValidateLogin,
} from "./app/config/context/redux/app-actions";
import {
  RootState,
  useTypedDispatch,
} from "./app/config/context/redux/app-store";
import AuthProtection from "./app/config/routes/AuthProtection";
import { getRoutes } from "./app/config/routes/routes";
import { Page404 } from "./infraestructure/delivery/presentation/pages/Page404";

function App() {
  const dispatch = useTypedDispatch();
  const auth = useSelector((state: RootState) => state.auth);

  useEffect(() => {
    dispatch(doValidateLogin());
    dispatch(doFetchParcels());
  }, [dispatch]);

  return (
    <BrowserRouter basename={process.env.PUBLIC_URL}>
      <AuthProtection auth={auth}>
        <Routes>
          <Route path="*" element={<Page404 />} />
          {getRoutes(auth).map((route, index) => (
            <Route
              key={index}
              path={route.path}
              element={
                <route.layout>
                  <route.component />
                </route.layout>
              }
            />
          ))}
        </Routes>
      </AuthProtection>
    </BrowserRouter>
  );
}

export default App;
